// <auto-generated />
namespace QRJ.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddUrlType : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddUrlType));
        
        string IMigrationMetadata.Id
        {
            get { return "201309022310126_AddUrlType"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
