// <auto-generated />
namespace QRJ.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class QRCodeViewedCategoryContentAddExpiresOn : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(QRCodeViewedCategoryContentAddExpiresOn));
        
        string IMigrationMetadata.Id
        {
            get { return "201309141756462_QRCodeViewedCategoryContentAddExpiresOn"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
